# Generated by Django 5.2.5 on 2025-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField(auto_created=True, auto_now_add=True)),
                ('jobno', models.CharField(max_length=5)),
                ('order_id', models.IntegerField()),
                ('cust_id', models.IntegerField()),
                ('taxable_amount', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('grandtotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobno', models.CharField(max_length=5)),
                ('account', models.CharField(max_length=100)),
                ('item_no', models.SmallIntegerField()),
                ('item', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
