# Generated by Django 5.2.5 on 2025-08-20 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='jobno',
        ),
        migrations.AddField(
            model_name='order',
            name='jobcard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.jobcard'),
            preserve_default=False,
        ),
    ]
