# Generated by Django 5.2.5 on 2025-08-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_jobcard_order_id_remove_order_jobno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='advance',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
