# Generated by Django 5.2.5 on 2025-08-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobcard_advance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='advance',
            field=models.FloatField(default=0.0),
        ),
    ]
