# Generated by Django 5.2.5 on 2025-08-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_jobcard_advance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type', models.CharField(max_length=10)),
                ('type_of_contact', models.CharField(max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('alt_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('taxable', models.BooleanField(blank=True, default=False, null=True)),
                ('gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_balance', models.FloatField(default=0.0)),
                ('closing_balance', models.FloatField(default=0.0)),
            ],
        ),
    ]
