# Generated by Django 5.2.5 on 2025-08-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='jobno',
            field=models.CharField(max_length=10),
        ),
    ]
