# Generated by Django 5.2.5 on 2025-08-23 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_jobcard_jobno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=50)),
                ('hsn_code', models.CharField(max_length=20)),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxrates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='app.taxrates')),
            ],
        ),
    ]
