# Generated by Django 5.2.5 on 2025-08-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_taxrates_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='jobno',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='taxrates',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=3, unique=True),
        ),
        migrations.AlterField(
            model_name='taxrates',
            name='slab',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
