# Generated by Django 5.2.5 on 2025-08-30 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_item_code_alter_item_hsn_code_alter_item_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cust_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
