# Generated by Django 5.2.5 on 2025-09-01 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contact_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='item',
            name='tax_preference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, default='nos', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='taxrates',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
