# Generated by Django 5.2.5 on 2025-09-02 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_item_item_id_item_tax_preference_item_type_item_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='jobcard_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
