# Generated by Django 5.2.5 on 2025-09-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_jobcard_jobcard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='taxrates',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
