# Generated by Django 5.2.5 on 2025-09-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_item_tax_rate_alter_item_taxrates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='taxrates',
        ),
    ]
