# Generated by Django 5.2.5 on 2025-09-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_item_taxrates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='account',
        ),
    ]
