# Generated by Django 5.2.5 on 2025-09-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_order_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
