# Generated by Django 5.2.5 on 2025-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='jobcard_id',
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
