# Generated by Django 5.2.5 on 2025-09-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_jobcard_jobcard_id_alter_jobcard_job_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='jobslug',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
