# Generated by Django 5.2.5 on 2025-09-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_jobcard_jobslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='unreg_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
