# Generated by Django 5.2.5 on 2025-09-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_jobcard_unreg_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='unreg_customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
